### ISSUE TITLE
https::// instead of https://

### ISSUE THREAD

**Issue by eserte** [rlauer6/perl-Amazon-API#5]
There are some places in documentation and code where "https:://" instead of "https://" is used (and in one case a slash is missing). See:
https://github.com/search?q=repo%3Arlauer6%2Fperl-Amazon-API+%22https%3A%3A%22&type=code

Also I think it would be a good idea to add "--depth=1" to the git-clone calls.

**Comment by rlauer6** [comment]
thanks - scheduled to be fixed in 2.0.13
